# Generated by Django 4.0.2 on 2022-06-01 12:50

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=250, verbose_name='full name')),
                ('username', models.CharField(db_index=True, max_length=200, unique=True, validators=[accounts.models.username_validator], verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('profile_picture', models.URLField(blank=True, max_length=500, verbose_name='profile picture')),
                ('is_private', models.BooleanField(default=False, verbose_name='is private')),
                ('superuser', models.BooleanField(default=False, verbose_name='is superuser')),
                ('staff', models.BooleanField(default=False, verbose_name='is staff')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('id', 'created_date'),
            },
        ),
    ]
