# Generated by Django 4.0.2 on 2022-06-01 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
